config/routes.rb
Trainbuddy::Application.routes.draw do

  resources :users, except: [:create]
  resources :profiles, only: [:edit, :update]
  resources :plans, except: [:index, :show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :index, :new]
  resources :mails
  resources :activities, only: [:show]

  resources :invitations, only: [:new, :create, :edit, :update, :show]


  # resources :relationships,p only: [:create, :destroy, :update]
  resources :relationships, only: [:updates, :index] do
      put :updates, on: :collection
  end

  resources :broadcasts, only: [:index, :destroy]
  resources :stations, only: [:index]


  
  get "map/index"
  
  get "pages/help"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  get '/u/:login',  to: 'users#show',    constraints: { login: /[a-z][a-z0-9]*(_|.){1}[a-z0-9]+/i }
  
  get '/signup',    to:   'users#new'
  get '/signin',    to:   'sessions#new'
  match '/signout', to:   'sessions#destroy',   via:  :delete
   

  get '/contact',   to:   'pages#contact'
  get '/about',     to:   'pages#about'
  get '/help',      to:   'pages#help'
  get '/feeds',     to:   'pages#home'
  get '/',          to:   'map#index'
  root              to:   'map#index'

end

app/views/share/_carousel.html.erb
<div id="carousel" class="carousel slide">

  <ol class="carousel-indicators">
    <li data-target="#carousel" data-slide-to="0" class="active"></li>
    <li data-target="#carousel" data-slide-to="1"></li>
    <li data-target="#carousel" data-slide-to="2"></li>
    <li data-target="#carousel" data-slide-to="3"></li>
    <li data-target="#carousel" data-slide-to="4"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">

    <div class="active item">
      <%= image_tag 'carousel/posting2.png', alt: 'query train time' %>
      <div class="carousel-caption">
        <h4>3 Ways to Query Train times</h4>
        <p>3 different ways to query the train time, so you pick the one you are comfortable with.</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag 'carousel/broadcast2.png', alt: 'find train times' %>
      <div class="carousel-caption">
        <h4>Find Train Time and Match Nearby Friends</h4>
        <p>Query train times and match with friends that travel nearby</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag 'carousel/map2.png', alt: 'train map'  %>
      <div class="carousel-caption">
        <h4>Train Map and Friend Locations</h4>
        <p>Display friends' locations within the train network</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag 'carousel/posts_2.png', alt: 'news feeds'  %>
      <div class="carousel-caption">
        <h4>Friend Location Feeds</h4>
        <p>News feed on the friends' travel plans</p>
      </div>
    </div>

    <div class="item">
      <%= image_tag 'carousel/stops2.png', alt: 'slide 3'  %>
      <div class="carousel-caption">
        <h4>Detail Stop Time</h4>
        <p>Find out the stop time on each of the stations</p>
      </div>
    </div>



  </div>

  <!-- Carousel nav -->
  <a class="carousel-control left" href="#carousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#carousel" data-slide="next">&rsaquo;</a>
</div>

app/views/share/_feed_item.html.erb
<li id="<%=feed_item.id%>">

  <div class="row-fluid">
    <div class="span3">
      <%= link_to(image_tag(feed_item.user.avatar.url(:thumb), class: "img-polaroid"), root_url+feed_item.user.to_permalink ) %>
    </div>

    <div class="span8">
      <% if current_user?(feed_item.user) %>
        <%=link_to('&times;'.html_safe, feed_item, method: :delete, class: "close", title: "delete" , data:{confirm: "Delete...?"})%>
      <%end%>

      <p><%=wrap feed_item.content %></p>
      <p class="opt_link_info"><%=gen_activity_link(feed_item.opt_link, @url.to_s)%></p>
    </div>

  </div>

  <div class="row-fluid">
    <div class="span3"><%=link_to feed_item.user.name, root_url+feed_item.user.to_permalink %></div>
    <div class="span8"><p class="content_datetime">Posted <%=time_ago_in_words feed_item.created_at%> ago</p></div>
  </div>

</li>

app/views/share/_feed_menu.html.erb
<% @post_opt ||= "11" %>
<ul class="smltabs">
 
  <li id= <%= @post_opt[0]=="1"? "smltabs_selected":"" %> >
	<%= link_to("All Updates",microposts_path(u_id: @user.id, posts: "1"+@post_opt[1]), {remote: true} ) %>
  </li>
  <li id= <%= @post_opt[0]=="2"? "smltabs_selected":"" %> >
  	<%= link_to("This User Only",microposts_path(u_id: @user.id, posts: "2"+@post_opt[1]), {remote: true} ) %>
  </li>


<% case @post_opt[1].to_i %>
<% when 0 %>
	<li id='expire_0'>
		<%= link_to("+ include expired", microposts_path(u_id: @user.id, posts: @post_opt[0]+"2"), {remote: true} )%>
	</li> 
<% when 2 %>
	<li id='expire_2'>
		<%= link_to("- only expired", microposts_path(u_id: @user.id, posts: @post_opt[0]+"1"), {remote: true} )%>
	</li>
<% else %>
	<li id='expire_1'>
		<%= link_to("+ only active", microposts_path(u_id: @user.id, posts: @post_opt[0]+"0"), {remote: true} )%>
	</li>
<% end %>
</ul>

app/views/share/_feeds.html.erb
<div class="span9">

  <% @posts ||= "11" %>
  <div class="row-fluid">
    <div class="span12 menu-bar">
      <div class="menu-tag"><%= gen_post_menu(@user.id, @posts.first, @posts.last, @url.path) %></div>
    </div>
  </div>
<!-- menu-bar separator  -->
  <div id="stops_times"><%= render 'share/pop-stops' if @stops%></div>
  
  <div class="row-fluid">
    <div class="tab-content feeds span12">
    
      <div class="row-fluid">
        <div class="span12">
          <% if @feed_items && @feed_items.any? %>
            <ul class="list-items posts">
              <%= render partial: 'share/feed_item', collection: @feed_items %>
            </ul>
          <% else %>
            <h5 style="margin: 2px 0 100px 20px;">NO feed item found.</h5>
          <% end %>
        </div>
      </div>

      <div class="row-fluid">
        <% if @feed_items %><div class="span8"><%= will_paginate @feed_items %></div><%end%>
      </div>

    </div>
  </div>

</div>

app/views/share/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div id="flash-message">
  	<div class="alert <%= "alert-" + key.to_s.downcase %>">
  	  <%= link_to('&times;'.html_safe, response.location, class: "close", id: "flash-message-close", data:{dismiss: "pop-display"} ) %>
  	  <h5><%= key %></h5>
	  <%= value.html_safe %>
  	</div>
  </div>
<% end %>

app/views/share/_pop-stops.html.erb
<div class="pop_display row-fluid" id="pop-stops">
  <div class="pop_contents span8 offset2">
    <%= link_to('&times;'.html_safe, @url.to_s, id:"pop-stops-close", class: "close", data:{ dismiss: "pop-stops"} ) %>

    <div class="row-fluid">
      <div class="span11 stop-times">
      	<% @stops.each_slice(5) do |five|%>

      	  <div class="s_name row-fluid">
      	  	<% five.each do |s| %>
      	  	  <div class="span2"><%= s["s_name"]%></div>
      	  	<% end %>
      	  </div>

      	  <div class="s_time row-fluid">
      	  	<% five.each do |s| %>
              <div class="span2"><%= s["stop_time"]%></div>
            <% end %>
      	  </div>

      	<% end %>
      </div>
    </div>

  </div>
</div>

app/views/share/_ruler.html.erb
<div class="row">
  <div class="span1 border-red">1</div>
  <div class="span1 border-orange">2</div>
  <div class="span1 border-yellow">3</div>
  <div class="span1 border-blue">4</div>
  <div class="span1 border-aqua">5</div>
  <div class="span1 border-green">6</div>
  <div class="span1 border-lime">7</div>
  <div class="span1 border-olive">8</div>
  <div class="span1 border-pink">9</div>
  <div class="span1 border-orchild">10</div>
  <div class="span1 border-voilet">11</div>
  <div class="span1 border-purple">12</div>
</div>

<div class="row-fluid">
  <div class="span1 border-red">1</div>
  <div class="span1 border-orange">2</div>
  <div class="span1 border-yellow">3</div>
  <div class="span1 border-blue">4</div>
  <div class="span1 border-aqua">5</div>
  <div class="span1 border-green">6</div>
  <div class="span1 border-lime">7</div>
  <div class="span1 border-olive">8</div>
  <div class="span1 border-pink">9</div>
  <div class="span1 border-orchild">10</div>
  <div class="span1 border-voilet">11</div>
  <div class="span1 border-purple">12</div>
</div>

app/views/share/_user_info.html.erb
<% if signed_in? %>
<ul>
  <li class="user">
	<%= image_tag current_user.avatar.url(:small) , size: "60x60" %>
  	<p class="username"><%= current_user.name %></p>
    <%= link_to "Edit", edit_user_path(current_user), class: "btn btn-inverse btn-small" %> 
    <%= link_to "Logout", signout_path, method: "delete", class: "btn btn-inverse btn-small"  %>
    
    
  </li>
  
  <li class="mailcounts" >
  	<a href="#">Unread Mails : <span>1</span></a>
  </li>

</ul>
<% end %>  