config/routes.rb
Trainbuddy::Application.routes.draw do

  resources :users, except: [:create]
  resources :profiles, only: [:edit, :update]
  resources :plans, except: [:index, :show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :index, :new]
  resources :mails
  resources :activities, only: [:show]

  resources :invitations, only: [:new, :create, :edit, :update, :show]


  # resources :relationships,p only: [:create, :destroy, :update]
  resources :relationships, only: [:updates, :index] do
      put :updates, on: :collection
  end

  resources :broadcasts, only: [:index, :destroy]
  resources :stations, only: [:index]


  
  get "map/index"
  
  get "pages/help"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  get '/u/:login',  to: 'users#show',    constraints: { login: /[a-z][a-z0-9]*(_|.){1}[a-z0-9]+/i }
  
  get '/signup',    to:   'users#new'
  get '/signin',    to:   'sessions#new'
  match '/signout', to:   'sessions#destroy',   via:  :delete
   

  get '/contact',   to:   'pages#contact'
  get '/about',     to:   'pages#about'
  get '/help',      to:   'pages#help'
  get '/feeds',     to:   'pages#home'
  get '/',          to:   'map#index'
  root              to:   'map#index'

end

app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  friend_id  :integer
#  status     :integer
#  alias_name :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Relationship < ActiveRecord::Base
  attr_accessible :status, :user_id, :friend_id, :alias_name
  belongs_to	:user,		class_name: "User"
  belongs_to	:friend, 	class_name: "User", foreign_key: "friend_id"

  validates :user_id, 		presence: true
  validates :friend_id, 	presence: true
  validates :status,		presence: true

  ALIAS = 5
  OWN = 4
  FRIEND = 3
  PENDING = 2
  REQUEST = 1
  STRANGER = 0
  BLOCKED = -1

  def self.status(owner_id, other_id)
  	return OWN if owner_id == other_id
  	return STRANGER unless res = find_relation(owner_id, other_id)
  	return res.status
  end

  def self.status_str(owner_id, other_id)
    case status(owner_id, other_id)
    when BLOCKED
      return "Blocked"
    when STRANGER
      return "Stranger"
    when REQUEST
      return "Requested"
    when PENDING
      return "Pending Acceptance"
    when FRIEND
      return "Friended"
    when OWN
      return "Own"
    end
  end

  def self.set_alias(user_id, other_id, nick)
    user_rel = lock.find_by_user_id_and_friend_id(user_id, other_id)
    if user_rel
      user_rel.alias_name = nick
      return user_rel.save
    else
      return false
    end
  end


  def self.request(user_id, other_id, nick=nil)
  	return OWN if user_id == other_id
  	res = REQUEST

    transaction do 
		  if other_rel = lock.find_by_user_id_and_friend_id(other_id, user_id)
		    case other_rel.status
		    when FRIEND
          res = FRIEND
          update_one_side(FRIEND, user_id, other_id, nick)
		    when BLOCKED
          update_one_side( REQUEST, user_id, other_id, nick)
        when PENDING
          other_rel.updated_at = Time.now
          other_rel.save!
          update_one_side( REQUEST, user_id, other_id, nick)
        when REQUEST
          update_one_side( FRIEND, user_id, other_id,  nick)
          other_rel.status = FRIEND
          other_rel.save!
          res = FRIEND
        end
      else
        create(status: PENDING, user_id: other_id, friend_id: user_id, alias_name: nil )
		    self.update_one_side( REQUEST, user_id, other_id, nick)
		  end
    end
      return res
  end


  def self.accept(user_id, other_id, nick=nil)
  	return OWN if user_id == other_id
  	res = -1
  	transaction do
  		if other_rel = lock.find_by_user_id_and_friend_id(other_id, user_id)
  		  case other_rel.status
  		  when FRIEND
  			update_one_side(FRIEND, user_id, other_id, nick)
  			res = FRIEND
  		  when REQUEST
  			other_rel.status = FRIEND
  			other_rel.save!
  			update_one_side(FRIEND, user_id, other_id, nick)
  			res = FRIEND
  		  end
  		end
  	end
  	return res
  end


  def self.unfriend(user_id, other_id)
  	return OWN if user_id == other_id
  	res = STRANGER
  	transaction do
  		other_rel = lock.find_by_user_id_and_friend_id(other_id, user_id)
  		if other_rel && other_rel.status == BLOCKED
  			res = BLOCKED
  		else
  			other_rel.destroy
  		end
  		
  		if user_rel = lock.find_by_user_id_and_friend_id(user_id, other_id)
  			user_rel.destroy unless user_rel.status == BLOCKED
  		end
  	end
  	return res
  end


  def self.block(user_id, other_id)
  	return OWN if user_id == other_id
  	res = BLOCKED
  	transaction do 
  		if user_rel = lock.find_by_user_id_and_friend_id(user_id, other_id)
  			if user_rel.status == BLOCKED
  				user_rel.destroy
          other_rel = lock.find_by_user_id_and_friend_id(other_id, user_id)
          other_rel.destroy if other_rel && other_rel.status != BLOCKED
  				res = STRANGER
  			else
  				user_rel.status = BLOCKED
  				user_rel.save!
  			end
  		else
  			create!(status: BLOCKED, user_id: user_id, friend_id: other_id)
  		end
  	end
  	return res
  end

  def self.find_relation(owner_id, other_id)
	 find_by_user_id_and_friend_id(owner_id, other_id)
  end



private
	def self.update_one_side(status, user_id, other_id, nick)
		rel = lock.find_by_user_id_and_friend_id(user_id, other_id)
		if rel
			rel.status = status
			rel.alias_name = nick
			rel.save!
		else
			create!(status: status, user_id: user_id, friend_id: other_id, alias_name: nick)
		end
	end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_filter :signed_in_user
  before_filter :allow_read, only: [:index]
  before_filter :allow_write, only: [:updates]
  before_filter :show_broadcast

  def index
    # type = params[:type]? params[:type] : "friends"
    # condit = load_condit(type)
    condit = load_condit(params[:type])

    @users = User.where("users.id in (#{condit})",{user: current_user.id})\
                  .includes(:reverse_relationships) \
                  .where("relationships.user_id=#{current_user.id} or relationships.user_id is null")\
                  .paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def updates
  	@user = find_other(params[:other])
  	has_error = false


  	if @user
  		case params[:op].to_i
  		when -1
  			Relationship.block(current_user.id, @user.id)
  			flash.now[:Success] = "User blocked"
  		when 0
  			Relationship.unfriend(current_user.id, @user.id)
  			flash.now[:Success] = "User removed from Friends"
  		when 1
  		  Relationship.request(current_user.id, @user.id)
        friend_request_mail(current_user, @user, params[:msg])
  		when 3 
  			Relationship.accept(current_user.id, @user.id, params[:nick])
  			flash.now[:Success] = "User added into friend list"
      when 5
        Relationship.set_alias(current_user.id, @user.id, params[:nick] )
        flash.now[:Success] = "Alias name updated"
  		else
  			has_error = true
  			flash.now[:Error] = "Unknow operation code"
  		end
      @url = URI(user_path(@user.id))
      @url.query = join_params(nil, @posts)
  	else
      flash.now[:Error] = "Can not find user with :id #{params[:other]}"
  		has_error = true
  	end

  	if has_error
  		redirect_to(root_path)
  	else
      @relation = Relationship.find_relation(current_user.id, @user.id)
  		respond_to do |format|
  			format.html { redirect_to @user }
  		 	format.js
  		end
  	end
  end


private
  def find_other(user_id)
  	res = User.find_by_id(user_id)
  	if res.nil?
  		flash[:Error] = "Can not find User with id (#{user_id.to_i})"
  		return nil
  	end
  	if current_user?(res)
  		flash[:Error] = "Can not create relationship with own"
  		return nil
  	end
  	return res
  end

  def load_condit(type)
    case type
    when "block"
      @title = "Blocked users"
      condit = %(select friend_id from relationships where status = -1 and user_id = :user)
    when "request"
      @title = "Requests"
      condit = %(select friend_id from relationships where status = 1 and user_id = :user)
    when "pending"
      @title = "Pending Confirmation"
      condit = %(select friend_id from relationships where status = 2 and user_id = :user)
    when "suggest"
      @title =  "Suggest Friends"
      condit = %(select a.friend_id from relationships f, relationships a 
                  where f.user_id = :user and f.status = 3
                  and   a.friend_id <> :user and a.status = 3
                  and   a.friend_id not in 
                  ( select friend_id from relationships where status = 3 and user_id = :user)
                  and f.friend_id = a.user_id
                )
    else
      @title = "Friends"
      condit = %(select friend_id from relationships where status = 3 and user_id = :user)
    end
  end

  def allow_read
    if current_user.profile.settings.friends < 1
      flash[:Error] = "Insufficient privilege on accessing user relationships"
      redirect_to root_path
    end
  end

  def allow_write
    if current_user.profile.settings.friends < 2
      flash[:Error] = "Insufficient privilege on create or modifying user relationships"
      redirect_to root_path
    end
  end


end

app/helpers/relationships_helper.rb
module RelationshipsHelper
  
  def sample_request_msg(user)
    return "" if current_user.nil? or user.nil?
    res = "Hi #{user.name},\n\n#{current_user.name} would like to connect and be-friend with you; to share updates and whereabouts together. \n\nPlease confirm your relations by visiting the links provided.\n\n\n"
  end
  

  def friend_request_mail(from, to, mail_body)
  	option_link = ['<b>Link to : </b><a href="', root_url, from.to_permalink, '">', from.name, "\'s Profile and Friend Request</a>"].join
  	m = Mail.new(owner: from, sender: from, sent_date: Time.now, status: 0,
  					subj: "Relationship Request by #{from.name}", body: mail_body, to_users: "#{to.id}=#{to.name};" )
  	m.save
  	Mail.send_mail(m, to) unless from.block_by?(to)
  	flash[:Success] = "Friend Request sent to #{to.name}"
  end

end

app/views/relationships/_accept.html.erb
<%= form_tag( updates_relationships_path, method: :put, remote: true) do  %>
  <%= link_to("Accept Friend", user_url(@user,relation: "accept"), id: "href-accept", class: "btn btn-small" ) %>
  
  <%= render 'relationships/pop-accept' %>

<% end %>

<% if params[:relation]=="accept" %>
  <% javascript_tag do %> 
    $(function(){
  	  $("div#pop-accept").slideDown("slow", "swing");
  	  return false;
  	});
  <% end %>
<% end %>

app/views/relationships/_block.html.erb
<%=form_tag( updates_relationships_path, method: :put, remote: true) do  %>
  <%=hidden_field_tag 'other', @user.id  %>
  <%=hidden_field_tag 'op', -1 %>
  <%if @relation && @relation.status == -1%>
    <%=submit_tag "Unblock User", data: {confirm: 'Remove block restriction... ?'}, class: "btn btn-small" %>
  <%else %>
    <%=submit_tag "Block User", data: {confirm: 'Block all contacts from this user... ?'}, class: "btn btn-small"%>
  <%end%>

<%end%>

app/views/relationships/_form.html.erb
<div class="span12 form-inline">
  <h5 class="form-header">User Actions</h5>
  
    <ul class="left">
      <% if @relation %>
        <% case @relation.status %>
        <% when 1 %>
          <li><%= render 'relationships/request'%></li>
          <li><%= render 'relationships/unfriend'%></li>
        <% when 2 %>
          <li><%= render 'relationships/accept'%></li>
          <li><%= render 'relationships/unfriend'%></li>
          <li><%= render 'relationships/block' %></li>
        <% when 3 %>
          <li><%= render 'relationships/unfriend' %></li>
          <li><%= render 'relationships/block' %></li>
        <% else %>
          <li><%= render 'relationships/block' %></li>
        <% end %>
      <% else %>
        <li><%= render 'relationships/request'%></li>
        <li><%= render 'relationships/block' %></li>
      <% end %>
    </ul>
  
</div>

app/views/relationships/_pop-accept.html.erb
<div class="pop_display pop_hidden row-fliud" id='pop-accept'>
  <div class="pop_contents span8 offset2">
    <div class="form-inline span8 offset2">
      <h5 class="form-header span12">Alias Name
        <%= link_to('&times;'.html_safe, @user, id:"pop-accept-close", class: "close", data:{ dismiss: "pop-accept"} ) %>
      </h5>
      <div class="popfull-content">
        <div class="control-group">
          <%= label_tag 'nick', "Customized Name for #{@user.name} :", class: "control-label" %>
          <%= text_field_tag 'nick', nil, :placeholder => @user.login %>
          <%= hidden_field_tag 'other', @user.id  %>
          <%= hidden_field_tag 'op', 3 %>
        </div>
        <div class="control-group">
          <%= submit_tag "Submit Request", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_pop-request.html.erb
<div class="pop_display pop_hidden row-fliud" id='pop-request'>
  <div class="pop_contents span8 offset2">
    <div class="form-inline span8 offset2">
      <h5 class="form-header span12">Send Request Message
        <%= link_to('&times;'.html_safe, @user, id:"pop-request-close", class: "close", data:{ dismiss: "pop-request"} ) %>
      </h5>
      <div class="popfull-content">
        <div class="control-group row-fluid">
          <%= text_area_tag 'msg', raw(sample_request_msg(@user)), 
              class: "span12", rows: "10" %>
        </div>
        <div class="control-group row-fluid">
          <%= submit_tag "Submit Request", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_related_users.html.erb
<% provide(:title, @title) %>
<div class="span10 offset1"><%= render "users/list_users" if @users %></div>
<%=javascript_tag do %>
$(function(){
  function disable_menu(title){
    switch(title){
      case "Blocked users" :
        option = 4;
        break;
      case "Requests" :
        option = 3;
        break;
      case "Pending Confirmation" :
        option = 2;
        break;
      case "Suggest Friends" :
        option = 5;
        break;
      default:
        option = 1;
        break;
    }
    $("div#relate-menu>a").removeClass("disabled");
    $("div#relate-menu>a:nth-child(" +option+ ")").addClass("disabled");
  }
  disable_menu("<%= @title %>");

});
<%end %>

app/views/relationships/_relationships.html.erb
<div id="friend_status">
  <% if defined? @user %>
    <strong>Relationship : </strong>  <%= current_user.friend_status_str(@user, current_user) %>
  <% end %>
</div>

app/views/relationships/_request.html.erb
<%= form_tag( updates_relationships_path, method: :put, remote: true ) do  %>
  <%= hidden_field_tag 'other', @user.id  %>
  <%= hidden_field_tag 'op', 1 %>

  <%= link_to(user_url(@user, relation: "request"), id: "href-request", class: "btn btn-small" ) do%>
    <% if @relation && @relation.status == 1 %>Resent Request<% else %>Add as Friend<% end %>
  <% end %>

  <%= render 'relationships/pop-request' %>


<% end %>

<% if params[:relation]=="request" %>
  <% javascript_tag do %> 
    $(function(){
      $("div#pop-request").slideDown("slow", "swing");
      return false;
	});
  <% end %>
<% end %>

app/views/relationships/_status.html.erb
<% if defined? @user %>
	<strong>Relationship : </strong><%= Relationship.status_str(current_user.id,@user.id) %>
<% end %>

app/views/relationships/_unfriend.html.erb
<%= form_tag( updates_relationships_path, method: :put, remote: true) do  %>
  <%= hidden_field_tag 'other', @user.id  %>
  <%= hidden_field_tag 'op', 0  %>
  <%= submit_tag "Unfriend", data: { confirm: 'Remove user from friends... ?'}, class: "btn btn-small"  %>
<% end %>

app/views/relationships/index.html.erb
<div class="span12">
  <h1>Relations</h1>

  <div class="row-fluid" style="border-bottom: 1px solid #aaa;" >
  	<div id="relate-menu" class="span11 offset1" style="float:left;">
	<%=link_to "Friends", relationships_path(type: "friends"), {class: "btn btn-small", remote: true} %> 
	<%=link_to "Pending", relationships_path(type: "pending"), {class: "btn btn-small", remote: true} %> 
	<%=link_to "Requested", relationships_path(type: "request"), {class: "btn btn-small", remote: true} %> 
	<%=link_to "Blocked", relationships_path(type: "block"), {class: "btn btn-small", remote: true} %> 
	<%=link_to "Suggest Friend", relationships_path(type: "suggest"), {class: "btn btn-small", remote: true} %> 
  	</div>
  </div>

  <div id="list-users" class="row-fluid" style="padding-top: 10px;">
    <%= render "related_users" %>
  </div>


</div>

app/views/relationships/index.js.erb
$('div#flash_message').html("<%== escape_javascript(render('share/flash_message')) %>");
$('div#list-users').html("<%== escape_javascript(render('relationships/related_users')) %>");

app/views/relationships/updates.js.erb
$('.pop_display').hide();
$('div#flash_message').html("<%== escape_javascript(render('share/flash_message')) %>");
$('div#relation_status').html("<%== escape_javascript(render('relationships/status')) %>");
$('#relation_form').html("<%== escape_javascript(render('relationships/form')) %>");
$('div#user_header').html("<%== escape_javascript(render('users/user_name')) %>");
$('#feeds').html("<%== escape_javascript(render('share/feeds')) %>");
<% flash.discard %>