config/routes.rb
Trainbuddy::Application.routes.draw do

  resources :users, except: [:create]
  resources :profiles, only: [:edit, :update]
  resources :plans, except: [:index, :show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :index, :new]
  resources :mails
  resources :activities, only: [:show]

  resources :invitations, only: [:new, :create, :edit, :update, :show]


  # resources :relationships,p only: [:create, :destroy, :update]
  resources :relationships, only: [:updates, :index] do
      put :updates, on: :collection
  end

  resources :broadcasts, only: [:index, :destroy]
  resources :stations, only: [:index]


  
  get "map/index"
  
  get "pages/help"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  get '/u/:login',  to: 'users#show',    constraints: { login: /[a-z][a-z0-9]*(_|.){1}[a-z0-9]+/i }
  
  get '/signup',    to:   'users#new'
  get '/signin',    to:   'sessions#new'
  match '/signout', to:   'sessions#destroy',   via:  :delete
   

  get '/contact',   to:   'pages#contact'
  get '/about',     to:   'pages#about'
  get '/help',      to:   'pages#help'
  get '/feeds',     to:   'pages#home'
  get '/',          to:   'map#index'
  root              to:   'map#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  login               :string(255)
#  email               :string(255)
#  phone               :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  password_digest     :string(255)
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  remember_token      :string(255)
#

class User < ActiveRecord::Base
  attr_accessible 	:email, :name, :login, :phone, :avatar, :login,
  					:password_digest, :password, :password_confirmation
  has_secure_password
  has_many :microposts,         dependent: :destroy
  has_many :relationships,      dependent: :destroy
  has_many :broadcasts,         dependent: :destroy

  has_many :plans,              dependent: :destroy
  has_one  :profile,            dependent: :destroy

  
  has_many :reverse_relationships, foreign_key: "friend_id", class_name: "Relationship", 
                                dependent: :destroy
  
  has_many :friends,      through: :relationships,         source: :friend, conditions: "status= 3"
  # has_many :friended_by,  through: :reverse_relationships, source: :user,   conditions: "status= 3"
  # has_many :blocked_by,   through: :reverse_relationships, source: :user,   conditions: "status= -1"
  # relationship.status = -1  -> blocked

  has_many :mails,          foreign_key: "owner", class_name: "Mail", dependent: :"destroy"
  has_many :sent_mails,     foreign_key: "owner", class_name: "Mail", conditions: "status = 0"
  has_many :unread_mails,   foreign_key: "owner", class_name: "Mail", conditions: "status = 1"
  has_many :incoming_mails, foreign_key: "owner", class_name: "Mail", conditions: "status <> 0"

  has_many :sent_invitations, foreign_key: "sender_id", class_name: "Invitation"

  before_save 		{ self.email.downcase! 
                    self.name.capitalize!
                    self.login.downcase!
                  }
  before_save     :create_remember_token
  after_create    :create_profile

  has_attached_file :avatar,    style:  { large: "100x100", thumb: "30x30", small: "60x60", },
                                url:    ":web_root/icons/:id/image.:extension",
                                path:   ":rails_root/public/icons/:id/image.:extension",
                                default_url: "avatar.png"


  validates :name,  			presence:true,   length: { maximum:  50 }

  validates :password, 			presence:true, length: { minimum: 6 }

  validates :password_confirmation, presence: true

  email_regex =   /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  phone_regex =   /[+|-|*]*\d+/i
  login_regex =   /^[a-z][a-z0-9]*(_|\.){1}[a-z0-9]+$/i

  validates :email,     		presence:   	true,
                        		format:     	{ with: email_regex },
                        		uniqueness: 	{ case_sensitive: false }
  validates :login,         uniqueness:   { case_sensitive: false,
                                            with: login_regex }
  validates :phone,         uniqueness:   { case_sensitive: false }


  validates_attachment_size :avatar, less_than: 500.kilobytes





  def to_permalink
    login ? "u/#{login}" : "users/#{id}"
  end


  def admin?
    return profile.settings.admin > 0
  end

  def level
    return profile.level
  end

  def suggest_friends
  end

  def common_friends(other)
  end

  def has_access?(other_id)
    return ((other_id == self.id) || friended_by?(other_id))
  end

  def friended_by?(other_id)
    return reverse_relationships.where("user_id =? and status = ?", other_id ,3)
  end

  def block_by?(other_id)
    return reverse_relationships.where("user_id =? and status = ?", other_id, -1)
  end

  def decrement_invit
    profile.decrement! :invitations
  end


private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def create_profile
    Profile.create(user_id: self.id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,    except: [:new, :create ]
  before_filter :allow_write,       only: [:update, :destroy]
  before_filter :auth_user,         only: [:edit, :update, :destroy]
  before_filter :show_broadcast
  
  def index
    if params[:q] && params[:q].length > 1
      # tokeninput: mod==mail > #new_mail OR mod=mate > #new_posting
      if params[:mod]=='mate'
        params[:q] = params[:q][1..-1] if params[:q][0] == "@" 
        @users =  pgsql_select_all("select * from search_mate( %s, '%s');" % [ current_user.id.to_s, params[:q] ])
      else
        @users = pgsql_select_all("select * from search_users(%s, '%s', NULL, NULL, 10);" % [ current_user.id.to_s, params[:q] ])
      end

      render json: @users
      
    elsif params[:term] && params[:term].length > 1
      # autocomplete = mod=login
      #@users = pgsql_select_all("select * from login_available('#{params[:term].downcase}');")
      
      if params[:term].length < 6 || params[:term].length > 18
        @users = [{value: '', label: 'NOT Available - length between 6 to 18 chars long'}]
      elsif params[:term] =~ /^[a-z][a-z0-9]*(_|\.){1}[a-z0-9]+$/i
        @users = pgsql_select_all("select * from login_available('%s');" % [ params[:term].downcase ] )
      else
        @users = [{value: '', label: 'NOT Available - Only allow (a-z,0-9) with (. or _) once within the login'}]
      end
      render json: @users

    elsif params[:commit] == "Find"
      if (params[:name].size>1 || params[:email].size>1 || params[:phone].size>1)
        name = params[:name].size>0 ? "'#{params[:name]}'" : "NULL"
        email = params[:email].size>0 ? "'#{params[:email]}'" : "NULL"
        phone = params[:phone].size>0 ? "'#{params[:phone]}'" : "NULL"

        res = pgsql_select_all("select * from search_users(#{current_user.id},#{name},#{phone},#{email}, 100);")

#     not sure if best to include eager loading. can't limit relationships.user_id = current_user
#     @user = User.include(:reverse_relationships).where(["User.id in (?)", res.map{|u| u["id"].to_i}])

        @users = User.where(['id in (?)', res.map{|u| u["id"].to_i } ]).paginate(page: params[:page], per_page: 5) if res
      else
        flash.now[:Error] = "Search text required at least 2 characters"
        @users = nil
      end

    else
      @users = nil
    end
  end


  def new
    # no public reg
  	# @user = User.new
  end

  def show
    error_msg = fetch_user
    if @user
      @relation = Relationship.find_relation(current_user.id, @user.id)
      @users = @user.friends.paginate(:page => params[:friend_page], :per_page => 6) if current_user.has_access?(@user.id)
      @posts = params[:posts]? "2" + params[:posts][1] : "21"
      @feed_items = read_allowed_postings(@user.id, @posts)
      @stop = params[:act]? pgsql_select_all("select * from find_stop_times(#{current_user.id}, #{params[:act]} );") : nil

      @url = URI(user_path(@user.id))
      @url.query = join_params(nil, @posts)
    else
      flash[:Error] = error_msg
      redirect_to root_path
    end
  end


  def create
  	@user = User.new(params[:user])
    @user.login = @user.login.downcase
  	if @user.save
  		flash[:Success] = "User was successfully created."
      sign_in @user
  		redirect_back_or(@user)
  	else
      flash.now[:Error] = list_errors @user
  		render 'new'
  	end
  end

  def edit

  end

  def update
    user_params = params[:user]
    
    if user_params[:login] && @user.login
      if @user.profile.settings.login < 2 || !current_user.admin? 
        user_params[:login] = @user.login
        flash[:Error] = "Insufficient privilege on changing user login - reset to default"
      else
        user_params[:login] = user_params[:login].downcase
      end
    end

    if @user.update_attributes(user_params)
      flash[:Success] = "User info updated"
      sign_in @user
      redirect_to @user
    else
      flash.now[:Error] = list_errors(@user)
      render 'edit'
    end
  end

  def destroy
    if current_user?(@user)
      flash[:Error] = "Can not delete own user"
    else
      @user.destroy
      flash[:Success] = "User #{@user.id} destroy"
    end
    redirect_to users_path
  end



private

  def fetch_user
    if params[:login] && params[:login].size > 5
      id_code = params[:login]
      @user = User.find_by_login(params[:login])
      error_msg =  @user ? nil : "User: Could not find User[ login = #{params[:login]} ]" 
    else
      id_code = params[:id]
      @user = User.find_by_id(params[:id])
      error_msg =  @user ? nil : "User: Could not find User[ id = #{params[:id]} ]" 
    end
    return error_msg
  end


  def allow_write
    if current_user.profile.settings.password < 2
      flash[:Error] = "Insufficient privilege on modifying user info"
      redirect_to root_path
    end
  end

  def read_allowed_postings(user_id, posts)
    if current_user.profile.settings.post < 1
      flash[:Error] = "Insufficient user privilege on accessing postings."
      return nil
    else
      sql = "select * from select_posts( #{current_user.id}, #{@user.id}, #{ posts[1]=='0' }, 100);"
      res = pgsql_select_all(sql)
      res ? Micropost.where('id in (?)', res.map{|m| m["post_id"].to_i }).paginate(page: params[:page], per_page: 10) : nil
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def user_login_path(user, link_text=nil, css_class="")
  	link_text = user.login ? user.login : user.name unless link_text

  	link_to(link_text, root_path+user.to_permalink, class: css_class).html_safe
  end


end

app/views/users/_custom_name.html.erb
<div id="custom-name" class="fade bottom in span12" >
  <div class="arrow"></div>
  <div class="popover-inner row-fluid">
    <h3 class="popnext-title">
      User Alias Name  
      <%= link_to('&times;'.html_safe, @user, id:"custom-name-close", class: "close", data:{ dismiss: "pop-display"} ) %>
    </h3>
    <div class="popover-content controls controls-row">
      <%= form_tag( updates_relationships_path, :method=>:put, :remote => true) do  %>
        <div class="input-append span12">
            <%= hidden_field_tag 'other', @user.id  %>
            <%= hidden_field_tag 'op', 5  %>
            <%= text_field_tag 'nick', nil, :placeholder => "Unique Name Required", class: "span9" %>
            <%= submit_tag "Save", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if params[:name] %>
  <%= javascript_tag do %>
  $(function(){
    $("div#custom-name").slideToggle("slow", "swing" );
  });
  <% end %>
<% end %>

app/views/users/_fields.html.erb
<div class="row-fluid">
  <div class="span2 offset1"><%= f.label :name%></div>
  <div class="span4"><%= f.text_field :name, class: "span12" %></div>
</div>
<div class="row-fluid">
  <div class="span2 offset1"><%= f.label :email %></div>
  <div class="span4"><%= f.text_field :email, class: "span12" %></div>
</div>
<div class="row-fluid">
  <div class="span2 offset1"><%= f.label :phone %></div>
  <div class="span4"><%= f.text_field :phone, class: "span12" %></div>
</div>
<div class="row-fluid">
  <div class="span2 offset1"><%= f.label :login %></div>
  <div class="span4">



    <% if params[:action] =~/new/ || current_user.admin? %>
      <%= f.text_field :login, class: "span12", data: {autocomplete_source: users_path(mod: "login")} %>      
    <% else %>
      <%= f.text_field :login, class: "span12", disabled: true %>    
    <% end %>



  </div>
  <div class="span4"><small>Login: 6-18 chars. Only allow a-z,0-9 and ('-' or '_') once within the login</small></div>
</div>
<div class="row-fluid">
  <div class="span2 offset1"><%= f.label :password %></div>
  <div class="span4"><%= f.password_field :password, class: "span12" %></div>
</div>
<div class="row-fluid">
  <div class="span2 offset1"><%= f.label :password_confirmation, "Retype Password" %></div>
  <div class="span4"><%= f.password_field :password_confirmation, class: "span12" %></div>
</div>
<div class="row-fluid ">
  <div class="span2 offset1">
    <%=f.label :avatar, "Upload photo" %>
  </div>
  <div class="span4">
        <%= image_tag(@user.avatar.url(:large), :size => "100x100", :class => "img-polaroid" ) %><br />
        <%= f.file_field :avatar %>
  </div>
</div>

app/views/users/_friends.html.erb
<div class="span12 form-inline">
  <h5 class="form-header"><%= @user.name%>'s Friends</h5>
  <div class="row-fluid">
    <div class="span12 thumb_alt" style="padding: 0 10px; ">
      <% if @users.empty? %>
        No user can be retrieved
      <% else %>
        <ul>
          <% @users.each do |u| %>
            <li><%=link_to(u) do%>
                  <%=image_tag(u.avatar.url(:thumb) )%>
                  <span class="desc"><%=u.name%></span>
                <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12 form-supp" >
      <%= will_paginate @users, param_name:'friend_page', class: "pagination pagination-mini pagination-centered" %>
    </div>
  </div>
</div>

app/views/users/_list_users.html.erb
<%if @users.nil? || @users.empty?%>
  <h2><strong>No user can be retrieve.</strong></h2>
<%else%>
  
  <div class="row-fluid"><div class="span9"><%= will_paginate @users %></div></div>

  <ul class="list-items">
    <% @users.each do |user| %>
      <li>
        <div class="row-fluid">
          <div class="span2">
            <%= link_to(image_tag(user.avatar.url(:small), class:"img-polaroid")+" #{user.login}", user ) %>
          </div>
          <div class="span6">
            <%= link_to('&times;'.html_safe, user, method: :delete, class: "close", data:{confirm: "Delete user ...?"} ) if current_user.admin? %>
            <h3><%= link_to user.name, user %></h3>
            <p>Relation : <%= Relationship.status_str(current_user.id, user.id) %></p>
          </div>
        </div>

      </li>
    <% end %>
  </ul>

<% end %>

app/views/users/_sign_up.html.erb
<div class="row-fluid">
  <div class="span11">
    <h1>Sign up</h1>
	  <%= form_for(@user, html: {multipart: true}) do |f| %>
      
      <%= render 'fields', f: f %>

  	  <div class="row-fluid form_submit">
		    <div class="span3 offset3" ><%= f.submit "Sign up", class: "btn btn-large btn-primary" %></div>
  	  </div>
    <% end %>
  </div>
  
  <div class="span1" id="flash_message"><%=render 'share/flash_message'%></div>
</div>

app/views/users/_user_name.html.erb
<h3 id="user_name"> <%= @user.name %>

<% if @relation %>
  <%= link_to( user_url(@user, name: true) , id: "cust-name-edit") do %>
    <span id="user-name-edit">Edit</span>
  <% end %>
  <% if @relation.alias_name and @relation.alias_name.size > 0%>
		- <small>  (<%= @relation.alias_name %>)</small>
  <% end %>
<% end %>
</h3>

<%= render 'users/custom_name' if @relation %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<div class="row-fluid">
  <div class="span10 offset1">
  	<h1>Edit User</h1>
	
	<%= form_for(@user, html: {multipart: true}) do |f| %>
      <%= render 'fields', f: f %>

      <div class="row-fluid form_submit">
	      <div class="span3 offset3" ><%= f.submit "Update",  class: "btn btn-large btn-info" %></div>
	      <div class="span4"><%= link_to 'Config Matching Profile Setting', edit_profile_path(@user.id) %></div>
      </div>
    <% end %>
  </div>

  <div class="span1" id="flash_message"><%=render 'share/flash_message'%></div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'User index') %>
<div class="row-fluid">
  <div class="span10 offset1">
    <h1>User Search</h1>
    <%=form_tag( { :action => "index" }, :method => "get") do  %>
      <div class="row-fluid">
        <div class="span2"><%= label_tag :name%></div>
        <div class="span8"><%=text_field_tag :name %></div>
      </div>

      <div class="row-fluid">
        <div class="span2"><%= label_tag :email%></div>
        <div class="span8"><%=text_field_tag :email %></div>
      </div>

      <div class="row-fluid">
        <div class="span2"><%= label_tag :phone %></div>
        <div class="span8"><%=text_field_tag :phone %></div>
      </div>

      <div class="row-fluid">
        <div class="span3 offset2"><%= submit_tag "Find" , class: "btn btn-primary" %></div>
        <div class="span5"><span class="smltxt"> * self can be omitted in search</span></div>
      </div>
    <% end %>
    <%= render 'users/list_users' if @users%>
  </div>

  <div class="span1" id="flash_message"><%=render 'share/flash_message'%></div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<!-- Not open to public -->

<div class="row-fluid">
  <div class="span7 offset1">
    <h3>Sorry....</h3>
    <h4>We don't accept public users at this moment</h4>
    <p>Due to the application is still in alpha testing stage, only users with invitation keys are allowed to sign-up.</p>
    <p>If you are interested, contact the site owner from methods listed at the <%= link_to 'contact', contact_path %> page </p>
  </div>
</div>

<!--
< render 'sign_up' >
-->

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row=fluid">
  <div class="span11">
    <div class="row-fluid">
      <div class="span2"><%=image_tag @user.avatar.url(:large), class: "img-polaroid"%></div>

      <div class="span5">
        <div class="row-fluid">
          <div id="user_header" class="span12"><%=render 'user_name'%></div>
        </div>
        <div class="row-fluid"><div class="span5" style="white-space:nowrap;">
          <% if current_user?(@user) %>
            <%=link_to "Setting", edit_user_path(@user), class: "btn btn-small" %>
            <%=link_to "Profile", edit_profile_path(@user.id), class: "btn btn-small" %>
          <%else%>
            <%=link_to(new_mail_path(to: @user.id), class:"btn btn-small" ) do%>
              <%=image_tag "email_draft.png", alt:"Send Msg"%> Send msg
            <%end%>
          <%end%>
        </div></div>
        <div class="row-fluid">
          <div class="span12" id="relation_status"><%=render "relationships/status"%></div>
        </div>
        <div class="row-fluid">
          <div class="span12"><strong>URL : </strong> <%=link_to root_url + @user.to_permalink %></div>
        </div>
      </div>

      <div class="span5">
        <div class="row-fluid"><%=render("users/friends") if current_user.has_access?(@user.id)%></div>
        <div id="relation_form" class="row-fluid"><%=render "relationships/form" unless current_user?(@user)%></div>
      </div>
    </div>

    <div class="row-fluid news" id="news"><%= render 'share/feeds' %></div>
  </div>


  <div class="span1" id="flash_message"><%=render 'share/flash_message'%></div>
</div>