config/routes.rb
Trainbuddy::Application.routes.draw do

  resources :users, except: [:create]
  resources :profiles, only: [:edit, :update]
  resources :plans, except: [:index, :show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy, :index, :new]
  resources :mails
  resources :activities, only: [:show]

  resources :invitations, only: [:new, :create, :edit, :update, :show]


  # resources :relationships,p only: [:create, :destroy, :update]
  resources :relationships, only: [:updates, :index] do
      put :updates, on: :collection
  end

  resources :broadcasts, only: [:index, :destroy]
  resources :stations, only: [:index]


  
  get "map/index"
  
  get "pages/help"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  
  get '/u/:login',  to: 'users#show',    constraints: { login: /[a-z][a-z0-9]*(_|.){1}[a-z0-9]+/i }
  
  get '/signup',    to:   'users#new'
  get '/signin',    to:   'sessions#new'
  match '/signout', to:   'sessions#destroy',   via:  :delete
   

  get '/contact',   to:   'pages#contact'
  get '/about',     to:   'pages#about'
  get '/help',      to:   'pages#help'
  get '/feeds',     to:   'pages#home'
  get '/',          to:   'map#index'
  root              to:   'map#index'

end

app/models/invitation.rb
# == Schema Information
#
# Table name: invitations
#
#  id              :integer          not null, primary key
#  sender_id       :integer
#  recipient_email :string(255)
#  token           :string(255)      not null
#  sent_at         :datetime
#  multiple        :integer          default(1)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Invitation < ActiveRecord::Base
  attr_accessible :recipient_email, :sender_id, :sent_at, :token, :multiple
  
  belongs_to :sender, class_name: "User", include: :profile

  validates_presence_of :sender_id
  validate :recipient_is_not_registered
  validate :sender_has_invitations, :if => :sender

  before_create :generate_token
  before_create :decrement_counts
  


  def recipient_is_not_registered
  	self.errors.add :recipient_email, 'is already registered' if User.find_by_email(recipient_email)
  end

  def sender_has_invitations
  	unless sender.profile.invitations > 0
  	  errors.add :base, 'Excessed max limit invitations for the user'
  	end
  end

  def generate_token
  	self.token = Digest::SHA1.hexdigest([sender.login, Time.now, rand].join)
  end

  def decrement_counts
  	sender.decrement_invit
  end

  def redempt_invit
    self.decrement! :multiple
  end


end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :edit]
  before_filter :new_user_only, only: [:show, :update]

  def new
  	if current_user.profile.invitations < 1
  	  flash[:Error] = "Insufficient invitations left. Increase your current level to gain more invitations."
  	  redirect_to edit_profile_path(current_user.id)
  	else
 	  @invitation = current_user.sent_invitations.build
  	end
  end

  def create
  	@invitation = current_user.sent_invitations.build(recipient_email: params[:email])
  	@invitation.multiple = params[:multiple] if current_user.admin?
  	if @invitation.save
  	  flash[:Success] = "invitation created."
  	  redirect_to edit_invitation_path(@invitation)
  	else
  	  flash.now[:Error] = list_errors @invitation
  	  render 'new'
  	end
  end

  def edit
  	@invitation = current_user.sent_invitations.find_by_id(params[:id])
  	unless @invitation
  	  flash[:Error] = "Invitation( #{params[:id]} ) could not be found, please create new one again."
  	  redirect_to edit_profile_path(current_user.id)
  	end
  end

  def show
  	# signup
  	@invitation = Invitation.find_by_token(params[:id])
  	if @invitation
  	  if @invitation.multiple > 0
  	  	@user = User.new
  	  	@user.email = @invitation.recipient_email if @invitation.recipient_email.size > 0
  	  else
  	  	flash[:Error] = "Invitation has expired."
  	  	redirect_to root_path
  	  end
  	else
  	  flash[:Error] = "Invitation( #{params[:id]} ) is NOT found."
  	  redirect_to root_path
  	end
  end

  def update
  	# create-user
  	invit = Invitation.find_by_token(params[:token_hash].to_s)
  	if invit && invit.multiple > 0
  	  @user = User.new(params[:user])
  	  @user.email = invit.recipient_email if invit.recipient_email.size>0
  	  if @user.save
  	  	@user.profile.update_attributes(invitation_id: invit.id)
  	  	invit.decrement! :multiple
  	  	
  	  	Relationship.request @user.id, invit.sender.id
        friend_request_mail(@user, invit.sender, sample_request_msg(@user))
  	  	sign_in @user
  	  	flash[:Success] = "User created..."
  	  	redirect_to root_path
  	  else
  	  	flash.now[:Error] = list_errors @user
  	  	render 'show'
  	  end

  	else
  	  flash[:Error] = "Invitation is not valid or expired, please request for new one."
  	  redirect_to root_path
  	end


  end

private
  def new_user_only
  	if signed_in?
  	  flash[:Error] = "You are already a registed user, please logout first if you still want to create another account."
  	  redirect_to root_path
  	end
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
  def invitation_message(invit_id)
  	invit = Invitation.find_by_id(invit_id)
  	res = "Hi, \n\n#{invit.sender.name} has asked you to join Trainbuddy. Please go to the link below to signup for your account.\n\n"
  	return [res, invitations_url.to_s, "/", invit.token.to_s].join
  end

end

app/views/invitations/edit.html.erb
<% provide(:title, 'Invitation') %>

<div class="row-fluid">

  <div class="span11">
    <div class="row-fluid">
      <div class="span10 offset1">
    	<h1>Invitation</h1>
    	<p>You can edit, copy and paste the text below and <b>email it to your friend yourself</b>.</p>
      <p>Please remember when modifying, NOT to change the invitation URL as it contains the invitation code.</p>
      </div>
    </div>

    <div class="row-fluid" style="padding: 20px;">
      <div class="span10 offset1">
      	<%=text_area_tag 'invitation_message', invitation_message(@invitation.id), rows: 8, class: "span12"%>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span5 offset1" ><%=link_to "Send more invitations", new_invitation_path%></div>
      <div class="span5"><%=link_to "Profile", edit_profile_path(current_user.id)%></div>
    </div>
  </div>

  <div class="span1" id="flash_message"><%=render 'share/flash_message'%></div>
</div>

app/views/invitations/new.html.erb
<% provide(:title, 'New Invitations') %>
<div class="row-fluid">

  <div class="span11">
    <h1>New Invitations</h1>
    <%=form_tag invitations_path, method: :post do%>
      <%=hidden_field_tag 'sender_id', current_user.id%>
      <div class="row-fluid">
      	<div class="span2 offset1"><%=label_tag :email, "Recipient Email"%></div>
        <div class="span5"><%=text_field_tag :email, nil, class: "span12"%></div>
      </div>
      <%if current_user.admin? %>
      	<div class="row-fluid">
      	  <div class="span2 offset1"><%=label_tag :multiple%></div>
      	  <div class="span5"><%=text_field_tag :multiple, 1, class: "span12"%></div>
      	</div>
      <% else %>
      	<%=hidden_field_tag 'multiple', 1 %>
      <% end %>
      <div class="row-fluid">
      	<div class="span5 offset3" style="text-align:right">
      	  <small><%=current_user.profile.invitations%> Invitation(s) left</small>
      	</div>
      </div>
      <div class="row-fluid">
        <div class="span2 offset3"><%= submit_tag "submit",  class: "btn btn-info" %></div>
      </div>
    <% end %>
  </div>
  
  <div class="span1" id="flash_message"><%=render 'share/flash_message'%></div>
</div>

app/views/invitations/show.html.erb
<%provide(:title, 'Invitated Signup')%>
<div class="row-fluid">
  <div class="span11">

    <div class="row-fluid">
      <div class="span12" style="margin: 20px 10px;">
      	<h1>Invitation Signup</h1>
      	<p>You have been invited to signup for trainbudy. Fill-in the details to create your own account.</p>
      </div>
    </div>

    <%= form_for(@user, {url: invitation_path, method: :put} ) do |f| %>
      <%=hidden_field_tag :token_hash, @invitation.token%>
      <div class="row-fluid">
        <div class="span2 offset1"><%=f.label :name%></div>
        <div class="span4"><%=f.text_field :name, class: "span12"%></div>
      </div>
      <div class="row-fluid">
        <div class="span2 offset1"><%= f.label :email %></div>
        <div class="span4"><%=f.text_field :email, class: "span12", disabled: @invitation.recipient_email.size>0  %></div>
      </div>
      <div class="row-fluid">
        <div class="span2 offset1"><%=f.label :phone%></div>
        <div class="span4"><%=f.text_field :phone, class: "span12"%></div>
      </div>
      <div class="row-fluid">
        <div class="span2 offset1"><%=f.label :login%></div>
        <div class="span4"><%=f.text_field :login, class: "span12"%></div>
        <div class="span4"><small>Login: 6-18 chars. Only allow a-z,0-9 and ('-' or '_') once within the login</small></div>
      </div>
      <div class="row-fluid">
        <div class="span2 offset1"><%=f.label :password%></div>
        <div class="span4"><%=f.password_field :password, class: "span12"%></div>
      </div>
      <div class="row-fluid">
        <div class="span2 offset1"><%=f.label :password_confirmation, "Retype Password"%></div>
        <div class="span4"><%=f.password_field :password_confirmation, class: "span12"%></div>
      </div>
      <div class="row-fluid ">
        <div class="span2 offset1"><%=f.label :avatar, "Upload photo" %></div>
        <div class="span4">
          <%= image_tag(@user.avatar.url(:large), :size => "100x100", :class => "img-polaroid" ) %><br />
          <%= f.file_field :avatar %>
        </div>
      </div>
      <div class="row-fluid" style="border-top: 1px solid #ccc; margin-top: 20px; padding: 20px;">
        <div class="span5 offset3" ><%= f.submit "Sign up", class: "btn btn-large btn-primary" %></div>
      </div>
    <% end %>


  </div>
  <div class="span1" id="flash_message"><%=render 'share/flash_message'%></div>
</div>

app/views/invitations/update.html.erb
<h1>Invitations#update</h1>
<p>Find me in app/views/invitations/update.html.erb</p>